"""Synthetic Gaussian pulse-train generation.

This module generates sampled time-domain signals made from Gaussian pulses.
generate_pulse_train returns three NumPy arrays:
    1) t:
        Sample times, used as the x-axis of the waveform.
    2) signal:
        Signal amplitudes, used as the y-axis of the waveform.
    3) arrival_times:
        True pulse-center times used to generate the waveform.

The returned arrival_times array is ground truth. Timing estimators operate on
the sampled signal and can be tested by comparing their estimated arrival times
against these known true pulse-center times.
"""

from __future__ import annotations

import numpy as np

# Helper function for _validate_generate_args. Checks 
# that a value is finite and raises a ValueError if not.
def _require_finite(name: str, value: float) -> None:
    if not np.isfinite(value):
        raise ValueError(f"{name} must be finite")

# Helper function for generate_pulse_train. Validates the input 
# parameters and raises a ValueError if any of them are invalid.
def _validate_generate_args(
    sample_rate: float,
    duration: float,
    pulse_rate: float,
    pulse_width: float,
    amplitude: float,
    baseline: float,
    clock_offset: float,
    clock_drift: float,
    jitter: float,
    dropout: float,
) -> None:
    for name, value in (
        ("sample_rate", sample_rate),
        ("duration", duration),
        ("pulse_rate", pulse_rate),
        ("pulse_width", pulse_width),
        ("amplitude", amplitude),
        ("baseline", baseline),
        ("clock_offset", clock_offset),
        ("clock_drift", clock_drift),
        ("jitter", jitter),
        ("dropout", dropout),
    ):
        _require_finite(name, value)

    if sample_rate <= 0.0:
        raise ValueError("sample_rate must be positive")
    if duration <= 0.0:
        raise ValueError("duration must be positive")
    if pulse_rate <= 0.0:
        raise ValueError("pulse_rate must be positive")
    if pulse_width <= 0.0:
        raise ValueError("pulse_width must be positive")
    if jitter < 0.0:
        raise ValueError("jitter must be non-negative")
    if not 0.0 <= dropout <= 1.0:
        raise ValueError("dropout must be between 0 and 1")


# Takes numeric parameters and returns a tuple containing three NumPy arrays:
# time values, signal values, and pulse arrival times.
#
# The time values are uniformly spaced according to the sample rate and duration.
# The signal values are generated by starting with a baseline and adding Gaussian
# pulses centered at the pulse arrival times.
#
# The pulse arrival times are determined by the pulse rate, clock offset,
# clock drift, jitter, and dropout parameters.
#
# The first two arrays are the x/y data for a sampled time-domain signal.
# The third array contains the true pulse-center times of the pulse train.
#
# The result is a sampled time-domain signal made of Gaussian pulses, with an
# accompanying array of true pulse arrival times. Tests can then compare timing
# estimates against those known true values.
def generate_pulse_train(
    sample_rate: float,
    duration: float,
    pulse_rate: float,
    pulse_width: float,
    amplitude: float = 1.0,
    baseline: float = 0.0,
    clock_offset: float = 0.0,
    clock_drift: float = 0.0,
    jitter: float = 0.0,
    dropout: float = 0.0,
    seed: int | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Generate a synthetic Gaussian pulse train.

    ``pulse_width`` is treated as the approximate full temporal width of each
    pulse, spanning about six Gaussian standard deviations.
    """

    # Before generating anything, call _validate_generate_args(...) 
    # using the input values that were passed into generate_pulse_train.
    _validate_generate_args(
        sample_rate,
        duration,
        pulse_rate,
        pulse_width,
        amplitude,
        baseline,
        clock_offset,
        clock_drift,
        jitter,
        dropout,
    )

    # Calculate the number of samples based on the sample rate and duration.
    sample_count = int(np.floor(sample_rate * duration))
    if sample_count < 2:
        raise ValueError("sample_rate and duration must produce at least two samples")

    # Create the time axis values, starting from 0 and spaced according to the sample rate.
    t = np.arange(sample_count, dtype=float) / sample_rate # t = time in seconds

    # Creates an array of length sample_count where every element equals baseline.
    signal = np.full(sample_count, baseline, dtype=float)
    rng = np.random.default_rng(seed)

    # Pulse rate is the pulse-train frequency.
    # nominal_arrivals are ideal pulse-center times without drift or jitter.
    # drifted_arrivals scale the nominal arrival times by (1 + clock_drift),
    # so the timing shift grows with arrival time.
    # arrival_times are the drifted arrivals with a constant clock offset added.
    # Random jitter and dropout can then be applied.
    period = 1.0 / pulse_rate
    nominal_arrivals = np.arange(period, duration, period, dtype=float)
    drifted_arrivals = nominal_arrivals * (1.0 + clock_drift)
    arrival_times = drifted_arrivals + clock_offset

    if jitter > 0.0:
        arrival_times = arrival_times + rng.normal(0.0, jitter, size=arrival_times.shape)
    if dropout > 0.0:
        keep = rng.random(arrival_times.shape) >= dropout
        arrival_times = arrival_times[keep]

    # Removes any pulse centers outside the time axis.
    arrival_times = arrival_times[(arrival_times >= 0.0) & (arrival_times < duration)]
    # Ensures they're sequenced in order, as jitter could shift them out of order.
    arrival_times.sort()

    # pulse_width is interpreted as approximately six Gaussian standard deviations.
    sigma = pulse_width / 6.0

    # Core waveform generation loop. For each pulse arrival time, add a Gaussian pulse to the signal.
    for arrival_time in arrival_times:
        # Gaussian function
        signal += amplitude * np.exp(-0.5 * ((t - arrival_time) / sigma) ** 2)

    return t, signal, arrival_times.astype(float, copy=True)